version: '3'

services:
  nebulafaro:
    image: nebula_faro
    privileged: true
    container_name: nebula_faro
    networks:
      custom_network:
        ipv4_address: 172.18.0.2
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375
      
  nebulaserver:
    image: nebula_server
    privileged: true
    container_name: nebula_server
    networks:
      custom_network:
        ipv4_address: 172.18.0.3
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375
      
  nebulaclient:
    image: nebula_client
    privileged: true
    container_name: nebula_client
    networks:
      custom_network:
        ipv4_address: 172.18.0.4    
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

