version: '3'

services:

  router:
    image: router
    privileged: true
    container_name: router
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./volumes:/volumes
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.254
      net-192.168.60.0:
        ipv4_address: 192.168.60.254
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375    
       
  faro:
    image: faro
    privileged: true
    container_name: faro
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./volumes:/volumes
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.3
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375   
      
  host2:
    image: host2
    privileged: true
    container_name: host2
    cap_add:
      - ALL

    volumes:
      - ./volumes:/volumes
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.2         
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375     

     
  host1:
    image: host1
    privileged: true
    container_name: host1
    cap_add:
      - ALL

    volumes:
      - ./volumes:/volumes
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.2
      
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375     




networks:
  net-192.168.60.0:
    ipam:
      config:
        - subnet: 192.168.60.0/24
  net-10.9.0.0:
    ipam:
      config:
        - subnet: 10.9.0.0/24

