version: '3'

services:
  nebulafaro:
    image: nebula_faro
    privileged: true
    container_name: nebula_faro
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./volumes:/volumes
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.254
      net-192.168.60.0:
        ipv4_address: 192.168.60.254
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375     
  
  nebulaserver:
    image: nebula_server
    privileged: true
    container_name: nebula_server
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./volumes:/volumes
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.2         
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375     

     
  nebulaclient:
    image: nebula_client
    privileged: true
    container_name: nebula_client
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./volumes:/volumes
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.2
      
    ports:
      - 4242
      - 4241
      - 4342
      - 80
      - 8080
      - 6444
      - 6443
      - 443
      - 5000
      - 23788
      - 2379
      - 2375     




networks:
  net-192.168.60.0:
    ipam:
      config:
        - subnet: 192.168.60.0/24
  net-10.9.0.0:
    ipam:
      config:
        - subnet: 10.9.0.0/24

