apiVersion: v1
kind: Pod
metadata:
  name: comp-pod
spec:
  containers:
    - name: comp
      image: toto001011/comp:latest
      ports:
        - containerPort: 5000


cat > kind-federation.yaml <<EOF

apiVersion: federation.k8s.io/v1beta1
kind: Federation
metadata:
  name: federete-comp
spec:
  hostCluster: federete-comp


EOF
