version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "k8s.gcr.io/pause:3.2"
    stats_collect_period = "10s"
    enable_selinux = false
  [plugins."io.containerd.grpc.v1.snapshotter"]
    [plugins."io.containerd.grpc.v1.snapshotter"].use_selinux = false
  [plugins."io.containerd.grpc.v1.events"]
    [plugins."io.containerd.grpc.v1.events"].address = "/run/containerd/containerd-events.sock"
  [plugins."io.containerd.grpc.v1.healthcheck"]
    [plugins."io.containerd.grpc.v1.healthcheck"].interval = "30s"
    [plugins."io.containerd.grpc.v1.healthcheck"].timeout = "5s"
  [plugins."io.containerd.grpc.v1.introspection"]
    [plugins."io.containerd.grpc.v1.introspection"].address = "/run/containerd/containerd-debug.sock"
  [plugins."io.containerd.grpc.v1.leases"]
    [plugins."io.containerd.grpc.v1.leases"].lease_check_interval = "1m"
    [plugins."io.containerd.grpc.v1.leases"].lease_ttl = "2m"
    [plugins."io.containerd.grpc.v1.leases"].heartbeat_interval = "100ms"
    [plugins."io.containerd.grpc.v1.leases"].renew_deadline = "2m"
    [plugins."io.containerd.grpc.v1.leases"].auto_renew = true
  [plugins."io.containerd.monitor.v1.cgroups"]
    no_prometheus = true

