#FROM alpine:latest
FROM docker:dind
LABEL maintainer="Salvatore Francesco Indino"

# Installazione dipendenze per Nebula
RUN apk update && apk upgrade && \
    apk add --no-cache bash git make cmake gcc musl-dev openssl-dev

RUN apk add --no-cache go
RUN apk update && apk add openssh
RUN apk --update --no-cache add openrc

    
# Copia dei file di configurazione necessari a nebula
WORKDIR /nebula



COPY ./ca.key  /nebula/
COPY ./ca.crt /nebula/
COPY ./host.crt /nebula/
COPY ./host.key /nebula/
COPY ./config.yaml /nebula/
COPY ./nebula /nebula/


RUN ifconfig

# Esposizione delle porte utilizzate da Nebula
EXPOSE 4242/tcp
EXPOSE 4242/udp

EXPOSE 4241/tcp
EXPOSE 4241/udp

EXPOSE 4243/tcp
EXPOSE 4243/udp

EXPOSE 22/tcp
EXPOSE 22/udp

# Install sudo package
RUN apk add --no-cache sudo
RUN apk update && apk add bind-tools

#RUN apk add update && apk add install -yq linux-modules-extra-$(uname -r)




WORKDIR /nebula







# Impostazione del comando predefinito per avviare Nebula
CMD ["./nebula", "-config", "/nebula/config.yaml"]

