FROM alpine:latest

RUN apk add --no-cache docker
RUN apk --update --no-cache add openrc #&& rm -rf /var/cache/apk/**

RUN mkdir -p /run/openrc
RUN touch /run/openrc/softlevel

#CMD ["rc-service", "docker", "start"]

